### ISSUE TITLE
Post Issue 1

### ISSUE THREAD

**Issue by natechris-devine** [Gabrielle-Joy/info3180-project2#2]
# Post
When a person clicks 'POST,' there is no feedback letting the person know that their post was added. I recommend we move back to the posting person's profile page or the explore page with a notice telling the user their post was added.

**Comment by natechris-devine** [comment]
I'm looking in the code and I do see that it's supposed to redirect to explore while stating success @RowAtk 

But it's not working for me at least. It didn't redirect even with a successful post

**Comment by RowAtk** [comment]
lol this was the issue i fixed

**Comment by RowAtk** [comment]
fixed the issue. the wrong variable 'res' was being used instead of 'data' in the 'make_post' function
